import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.sass";
import { Lang } from "@/components/Lang";
import type { NextPage, GetStaticProps } from "next";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Form } from "@/components/Form";
import { Video } from "@/components/Video";
import { InNumbers } from "@/components/InNumbers";
import { SMM } from "@/components/SMM"
import { Service } from "@/components/Service";
import { Partners } from "@/components/Partners";
import { Work } from "@/components/Work";
import { About } from "@/components/About";
import { useInView } from 'react-intersection-observer';
import { useRef, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [workInView, setWorkInView] = useState(false);
  const smmRef = useRef(null);
  const { ref, inView } = useInView({
    threshold: 0.5,
    triggerOnce: true,
    onChange: (inView) => setWorkInView(inView),
  });

  return (
    <>
      <Head>
        <title>MainStream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/seoimg.png" />
      </Head>
      <Navbar />
      <Video />
      <Service />
      <InNumbers />
      <Partners />
      <Work />
      <SMM />
      <About />
      <Form />
      <Footer />
      {/* <Lang /> */}
    </>
  );
};


export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      messages: (await import(`../messages/${locale}.json`)).default,
    },
  };
};